### ISSUE TITLE
iCloud Sync not working (tried on last 3 releases)

### ISSUE THREAD

**Issue by mymatejackson** [dayanch96/InfusePlus#28]
iCloud Sync not working, just perpetually "Syncing with iCloud" - no data is added to iCloud. Have tried with last 3 previous installs. 

Installed via Sideloadly
iPhone 13 Pro Max
iOS 17.2.1

Thank you for your amazing work!

**Comment by dayanch96** [comment]
iCloud sync doesn’t work on sideloaded apps at all
