### ISSUE TITLE
[Feature Request] Support tvOS too 

### ISSUE THREAD

**Issue by GuyKh** [dayanch96/InfusePlus#44]
As a tvOS owner, without an Iphone, I'd love to see this for tvOS as well.

**Comment by dayanch96** [comment]
sorry, i don’t have tvOS to work with

**Comment by GuyKh** [comment]
😢

**Comment by tristan-k** [comment]
If I can get infuse.ipa for tvOS can I just follow the instructions at [Making your own InfusePlus IPA](https://gist.github.com/EshayDev/a981db7e87fbecf780ca943ecb5321d1)?

**Comment by dayanch96** [comment]
sadly, no

**Comment by tristan-k** [comment]
Thanks for clearing that up.
