### ISSUE TITLE
Add File dialog freezes up the app when FTP is clicked

### ISSUE THREAD

**Issue by XynoCrest** [dayanch96/InfusePlus#48]
If you navigate to “Add Files” from the file screen and select “FTP,” the app freezes completely, requiring a restart to resolve the issue.

- My local network permissions are enabled
- The IPA is obtained through your telegram (Dan’s Workshop)
- The IPA is signed using ESign
- The issue is not present in the original app

**Comment by dayanch96** [comment]
Sideloading issue

**Comment by XynoCrest** [comment]
I have tried older versions of the app with a different tweak and the same sideloading method, and it doesn’t have the issue.

**Comment by dayanch96** [comment]
Sorry, i wish but really can’t help with this issue
