### ISSUE TITLE
4k playback on demand Pro version

### ISSUE THREAD

**Issue by Deci8BelioS** [dayanch96/InfusePlus#9]
When playing a movie that I have in emby in 4k h265 on an iPhone 8 with palera1n and the latest update of the tweak asks me to activate the pro version and does not let me play it.

**Comment by dayanch96** [comment]
how can i test it?

**Comment by dayanch96** [comment]
Should it be from Emby server or I can play any 4k video by direct link?

**Comment by Deci8BelioS** [comment]
> Should it be from Emby server or I can play any 4k video by direct link?
> 
> And what about InfusePlus 1.0.2? Same issue?

This has happened to me in the last version of the tweak you posted, regarding the 4k issue it is possible that it has nothing to do with emby, that is, you could try it with direct link, I think it would appear to activate the infuse Pro.

**Comment by dayanch96** [comment]
I dont have any servers so have to figure out how to test it

**Comment by Deci8BelioS** [comment]
you can try directly from google drive, ftp, smb, webdav, dropbox, wherever, the app accepts many services xd

**Comment by dayanch96** [comment]
oh, so any 4k video shows you pro banner?

**Comment by Deci8BelioS** [comment]
I just tried version 1.0.2 of the tweak and indeed plays without problems, in 1.1 any playback so I've tested even with 1080p banner appears in the screenshot I passed before

**Comment by Deci8BelioS** [comment]
When installing the latest version (.deb rootless) it asks again to activate the Pro version to play any content.

**Comment by dayanch96** [comment]
Something wrong there because it works without any problems on my side. Rootful and Non-JB sideloaded ipa

https://github.com/dayanch96/InfusePlus/assets/38832025/c54baa42-605f-4fae-ac7c-d74921a8ca88

**Comment by Deci8BelioS** [comment]
Tweak version 1.0.2
https://github.com/dayanch96/InfusePlus/assets/96150975/1ac91c76-6248-432e-8dae-0c39f2f99139

Tweak version 1.1
https://github.com/dayanch96/InfusePlus/assets/96150975/637da61a-ab04-4044-9cb8-ed8b21dd84b1

**Comment by dayanch96** [comment]
can you try using sideloaded ipa as well?

**Comment by Deci8BelioS** [comment]
> can you try using sideloaded ipa as well?
> 
> you can even install it with changed bundle id

I just installed the IPA with trollstore and the same thing is happening to it

**Comment by dayanch96** [comment]
@Deci8BelioS try new release please

**Comment by Deci8BelioS** [comment]
> @Deci8BelioS try new release please

Now it works, the banner no longer appears.

**Comment by Deci8BelioS** [comment]
Works without problems with 1080p and 4k

Thank you very much for your work!

I close the issue, if I find any other bug I will open another one.
